### ISSUE TITLE
点击完成订购，网站就会卡死。

### ISSUE THREAD

**Issue by ytidc** [kesuki/whmcs-shadowsocks-plugin#14]
我想问下，自定义流量那里默认是1元1G，我该在哪里改呢

**Comment by ytidc** [comment]
但是不会自动开通

**Comment by ghost** [comment]
检查系统日志 如果有发现错误请复制到本issue

**Comment by ytidc** [comment]
@zzm317 搞好了，谢谢大佬，我想问下，自定义流量那里默认是1元1G，我该在哪里改呢

**Comment by ghost** [comment]
設置 產品/服務 可配置選項裡面
具體可以搜索下

**Comment by ytidc** [comment]
@zzm317 我知道设置方法，就是那里，默认是按1g流量叠加的，我想设置成，叠加一次，比如5g

**Comment by ghost** [comment]
options改成5试试

**Comment by ghost** [comment]
还有这个issue不是bug的话这个issue我就关掉了

**Comment by ytidc** [comment]
@zzm317 options麻烦能说下这个是在哪里修改吗

**Comment by ytidc** [comment]
@zzm317 直接填5不行，需要什么格式吗
