### ISSUE TITLE
请问新加的API有什么用

### ISSUE THREAD

**Issue by ytidc** [kesuki/whmcs-shadowsocks-plugin#17]

**Comment by ghost** [comment]
能不能把前與這個項目的issue發到我那邊
都說了我收不到郵件
而且開發狀態下的東西我不會pullrequest過來
還有 看readme啊

**Comment by ghost** [comment]
https://github.com/zzm317/Unlimited-Socks 要问开发中的东西能不能给我去这里开issue 
不然大家看了都是一脸懵逼
我还在想我什么时候开了pullrequest把api和adminpanel上传进去

**Comment by ghost** [comment]
https://github.com/zzm317/Unlimited-Socks/blob/master/Api/ReadMe.md
API的readme 能不能问我之前看下readme先？

**Comment by ytidc** [comment]
@zzm317 主要你那边不好发issues，那目前那个api能用了吗

**Comment by ghost** [comment]
开issue权限了

**Comment by ytidc** [comment]
@zzm317 前面一直想在你那边发，可是发不了，没有办法。请问API项目可以用了吗

**Comment by ghost** [comment]
Progress 40% |进度 40%
MainFrame 50%|主框架 50%
