### ISSUE TITLE
希望增加一个续费时流量重置功能

### ISSUE THREAD

**Issue by sine233** [kesuki/whmcs-shadowsocks-plugin#18]
冒昧给dalao提个请求
每月1号重置流量，会使部分用户在月中购买，获得所谓的双倍流量
有的用户觉得不公平，我也很为难_(:з」∠)_
再次感谢dalao的插件，很好用

**Comment by ghost** [comment]
下一步会增加按照购买日期清空流量的功能
届时会更新cron.php
还有实验性功能的issue开我那边=-=
要我说多少次我可能会收不到邮件

**Comment by sine233** [comment]
好的，刚刚没看到地址，现在已收藏

**Comment by ghost** [comment]
https://github.com/zzm317/Unlimited-Socks/blob/master/Crons/APIbandreset.php
