### ISSUE TITLE
重置流量

### ISSUE THREAD

**Issue by likky** [kesuki/whmcs-shadowsocks-plugin#2]
1. 如何让包季或包年用户每月购买日下载和上传流量重置为0，未到期每月重置流量。
2. 产品到期暂停时也需要重置下载和上传流量，否咋续费开通时流量还是上次使用的流量。
这个我已经实现。shadowsocks_SuspendAccount里面增加重置语句。

**Comment by SBgfw** [comment]
楼主你好
代码可以贴出来看下吗？

**Comment by ghost** [comment]
充值流量应该通过外部脚本实现，如需按购买日重置流量，需要修改sql，增加一栏保存购买日这个参数，已增加每月月初重置流量的方法，详情见博客文章

**Comment by likky** [comment]
感谢问题解决，关闭issue
