### ISSUE TITLE
您好，SSR 4.5 以上版本扫码二维码无法识别。

### ISSUE THREAD

**Issue by 123hehehe321** [kesuki/whmcs-shadowsocks-plugin#20]
您好，SSR 4.5 以上版本扫描二维码无法识别增加。  
请问怎么解决？
谢谢

**Comment by ghost** [comment]
由于ssr文档过于稀少，并且我个人的测试用ssr版本停留在4.2.3
故暂时无法测试和解决
可以的话 发一个完整的ssr链接给我让我看下

**Comment by ghost** [comment]
提供一个4.5以上版本的ssr链接，使用如下设置
ip test.test.test
password password
method aes-128-ctr
prot auth_aes128_md5
protparam aaabbb
obfs tls1.2_ticket_auth
obfsparam cccddd

**Comment by ghost** [comment]
还有 修bug什么的的issue 麻烦去那边也提一下 
要说多少次 容易收不到邮件

**Comment by 123hehehe321** [comment]
您好，初次使用 github 不太明白怎么弄。
我把资料发您QQ邮箱上？
