### ISSUE TITLE
关于流量叠加包和ping测试问题

### ISSUE THREAD

**Issue by byxinyu** [kesuki/whmcs-shadowsocks-plugin#26]
在模块设置开启了ping测试和启用流量包，用户购买后界面没有显示叠加包和ping操作界面，
所以插件数据都设置正确

**Comment by ghost** [comment]
請確定設置了cardconfig.php 把cardenable設置成了true
關於ping測試請提供具體描述 無法理解你的 沒有顯示ping操作界面

**Comment by byxinyu** [comment]
检查cardconfig.php，确实没有开启，我开启了用户ping，用户界面不能显示ping测试
最后感谢回复，国庆快乐

**Comment by ghost** [comment]
手机端访问的情况下不会显示ping测试 请使用电脑端
