### ISSUE TITLE
关于二维码的bug

### ISSUE THREAD

**Issue by goolissfun** [kesuki/whmcs-shadowsocks-plugin#27]
最近搭建，发现点击“查看url”显示只有一个s，二维码扫描结果也只有一个s。
ping测试为2340 error，请问这是什么问题呢？
whmcs7.23，ss后台用的是https://github.com/ssrbackup/shadowsocks-rss/wiki/Server-Setup(manyuser-with-mysql)

**Comment by ghost** [comment]
ping测试需要服务器有http支持
链接和url少一个s的问题我这边没有复现 建议下载release版测试
