### ISSUE TITLE
测试起来服务开通不了

### ISSUE THREAD

**Issue by meqi5120** [kesuki/whmcs-shadowsocks-plugin#28]
服务器那边数据库可以连上，产品配置那块也是按照图片来配置的，后台测试开通不了服务，后台系统日志显示 Module Create Failed - Service ID: 14 - Error: Array   一般是什么问题导致的呢。。。

**Comment by ghost** [comment]
能提供更加完整的日志么

**Comment by kozora** [comment]
我和你一样的问题

**Comment by ghost** [comment]
数据库导入没有

**Comment by kozora** [comment]
因为从神奇海螺那个上来的，直接用的user_usage.sql那个文件，然后跑起来了，可以进行重置操作，但就是无法createAccount操作

**Comment by kozora** [comment]
```
模块命令错误
WyIwMDAwMCIsbnVsbCxudWxsXQ==
```
直接在后台去创建的话会有这个报错
