### ISSUE TITLE
关于MuAPI

### ISSUE THREAD

**Issue by dz-paji** [kesuki/whmcs-shadowsocks-plugin#30]
不知道有没有兴趣适配MuAPI呢?

**Comment by ghost** [comment]
那是什么

**Comment by dz-paji** [comment]
就是通过网页api实现ss/ssr服务的开启。不需要数据库了

**Comment by ghost** [comment]
你是说sspanel？

**Comment by dz-paji** [comment]
不是啊 panel还是一个程序，但是muAPI仅仅是个api
这里有文档 https://sspanel.xyz/docs/muapi/v2

**Comment by ghost** [comment]
太麻烦了 这个api如果服务器被墙或者网络状态不好就会丢包失败 容错太低 并且为什么我要单独再去对接另外一套程序的api 在我能只通过数据库操作更新ss的用户数据的情况下

**Comment by dz-paji** [comment]
行吧

**Comment by ghost** [comment]
whmcs的php没有后台处理 一旦你维护服务器导致无法回包 将导致维护期间所有的增减用户操作失效 并且多服务器情况下 定时任务无法保证正常有效的执行
如果是sspanel单独用 我不建议你对接whmcs muapi不够完善 除非你是想做whncs对接ep或者solusvm这种才有意义

**Comment by dz-paji** [comment]
嗯嗯 谢谢指教

**Comment by ghost** [comment]
而且这套api没有增减用户 至少你给我的文档是这样 也没法对接
