### ISSUE TITLE
二维码弹窗的问题

### ISSUE THREAD

**Issue by Qinmei** [kesuki/whmcs-shadowsocks-plugin#4]
你好，使用的是neworld的开源面板，但是发现会在点击二维码时，图片会显示在页面底部，而不是直接弹出来，f12发现是缺少layer.css，从官网下载放入后，可以正常弹出，但是会有一定的错位，希望有空时能够查看一下，感谢开源

**Comment by beibaodong** [comment]
使用whmcs自带模板也会出现二维码图片显示在页面底部的问题。浏览器是最新版chrome

**Comment by ghost** [comment]
那个layer.js不知道为啥有这问题，你们可以改一下代码，用slimbox2.js做弹窗就没问题了。

**Comment by beibaodong** [comment]
博主你就给改一下呗，css  js我不会呀

**Comment by ghost** [comment]
此问题应该是已修复，建议close issue
