### ISSUE TITLE
SSR二维码不规范

### ISSUE THREAD

**Issue by XYenon** [kesuki/whmcs-shadowsocks-plugin#5]
SSR使用的链接是[URL safe base64，且不带padding（没有末尾的等于号）](https://github.com/breakwa11/shadowsocks-rss/wiki/SSR-QRcode-scheme)现在生成的二维码无法被最新版SSR C#客户端识别。
主要是用"-" "_"代替"+" "/"，还有不要在末尾加等号

**Comment by ghost** [comment]
以前的客户端我测试过是可以识别，如果最新版有改动，可以在details.tpl里面第103行自己修改。

**Comment by XYenon** [comment]
不是传进去的数据有问题，是生成的base64不是SSR要求的格式，在script.js第40行用"-" "_"代替"+" "/"，去掉第60行和第52行

**Comment by ghost** [comment]
确实旧的有生成不规范导致无法识别的问题
建议参照最新的进行修改

**Comment by williamnie** [comment]
今天我按照上面的方法修改了js文件.但是二维码还是不能识别,用浏览器的二维码扫描可以读出数据,数据没问题,通过剪切板导入可以使用,但直接用客户端还是无法识别,我用-_替换了+\,也把52和60行删掉了,请问大佬们知道是哪里的问题么

**Comment by ghost** [comment]
使用的是ssr還是ss
腳本和tpl修改了傳參部分
可以對比檢查下

**Comment by williamnie** [comment]
我现在还是用的是旧版本,没有更新,以前我的二维码是可以用的,但是今天有客户反映不能用了,才发现,新版本和旧版本跟新很多,我在研究下,谢谢您的回复

**Comment by ghost** [comment]
如果需要更多幫助可以給我直接發郵件到我github的郵箱 然後附上截圖 也可以加我qq（

**Comment by ghost** [comment]
此问题应该是已修复，建议close issue
