### ISSUE TITLE
修正了bug并增加了部分功能

### ISSUE THREAD

**Issue by ghost** [kesuki/whmcs-shadowsocks-plugin#6]
是否需要提个pullrequest还是建立个新分支还是自立新项目？

**Comment by kesuki** [comment]
提一个Pull requests过来，我合并进来

**Comment by ghost** [comment]
主要是还没做好ssr/ss切换呢。。。现在适配的ssr

**Comment by ghost** [comment]
(:3[___])做好了 如果可以的话测试下再合并吧

**Comment by kesuki** [comment]
你这个太多文件了，没办法合并，我主要是没有了whmcs的测试环境，没办法弄了，你应该用fork我这个代码，然后修改完不过，再提个Pull requests，不是在你现在的代码上提。

**Comment by ghost** [comment]
你原先那个没按文件夹分开 略显混乱 所以重新做了文件夹分类
所以实际上没多加多少=-=
