### ISSUE TITLE
从旧版本更新问题

### ISSUE THREAD

**Issue by williamnie** [kesuki/whmcs-shadowsocks-plugin#8]
我今天刚看到代码更新很多,数据表也更新了,我现在用的还是最开始的旧版本,可以直接全部替换更新么,我以前数据表里的用户数据就无法使用了,相当于新的一样,大佬指点一下

**Comment by ghost** [comment]
數據表更新是添加了數據庫 不修改可以用的
我會在電腦修好以後更新一下數據庫文件的

**Comment by ghost** [comment]
你可以備份一下舊的插件文件然後備份數據庫
之後上傳新插件，不要更新數據庫文件即可

**Comment by ghost** [comment]
新的數據庫和舊的相比加入了一個user_usage的數據表 是用來記錄用戶使用數據的 不添加問題不大

**Comment by ghost** [comment]
啊我想起来了，就是换完要把产品重新设置一下

**Comment by ghost** [comment]
更多需要注意的信息已更新至README.md

**Comment by williamnie** [comment]
谢谢大佬的及时回复，十分感谢，我晚上去试试，更新

**Comment by williamnie** [comment]
close
