### ISSUE TITLE
关于ping测试按钮

### ISSUE THREAD

**Issue by sine233** [kesuki/whmcs-shadowsocks-plugin#9]
首先感谢大佬提供的插件_(:з」∠)_
我已经从旧版本换上了新版本
体验下来发现ping测试按钮并不准确（服务器关闭了还显示√）
能否显示为ms
还有节点名称如果为中文 在软件上是乱码
最后再次十分感谢=￣ω￣=

**Comment by ghost** [comment]
ping那個我也發現了 下一個版本會去除改用其他方式
中文問題的話 把主php文件改成utf-8試試？
可能是我上傳的時候忘改了
如果問題復現請直接回覆我去查錯

**Comment by sine233** [comment]
今早起来 开通产品出错SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'ss1'

**Comment by ghost** [comment]
模塊設置裡面 服務器設置 看看是不是沒設置

**Comment by ghost** [comment]
產品/服務 模塊設置

**Comment by sine233** [comment]
设置了 会不会是数据库的问题 我没更新数据库

**Comment by ghost** [comment]
這個不會的 那個錯誤是模塊沒有查詢到configoption裡面的數據庫設置

**Comment by ghost** [comment]
你看下訂單裡面 服務器是不是設置了無

**Comment by ghost** [comment]
然後就是 因為模塊改了一下名字 你要檢查下服務器設置啊 產品設置啊裡面的模塊是不是新的名字（

**Comment by sine233** [comment]
我重启了一下服务器 ok了  感谢大佬及时回复_(:з」∠)_

**Comment by ghost** [comment]
ping测试部分修改了，pull了不过需要时间应该 你可以去我fork的那边下载新的然后测试

**Comment by sine233** [comment]
好的 (｡◕◡◕｡)ﾉ非常感谢
